title: Dahe Oh | Frontend developer (also designer) from Seoul
email: dahe.oh@gmail.com
description: Dahe Oh is a frontend developer and multi disciplinary designer from Seoul.
baseurl: "/"
url: "https://yogicat.dev"
github_usename: yogicat
google_analytics: UA-127168148-1

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

highlighter: rouge

permalink: /:year/:month/:title.html


jekyll_compose:
  draft_default_front_matter:
    categories: blog
    tag: [programming,today,recommend]
  post_default_front_matter:
    categories: blog
    tag: [programming,today,recommend]
    published: false

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
